# Generated by Django 4.1.13 on 2024-10-31 17:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='Город')),
                ('address', models.CharField(db_index=True, max_length=200, verbose_name='Адрес склада')),
                ('description', models.TextField(verbose_name='Описание')),
                ('road', models.TextField(verbose_name='описание проезда')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Контактный телефон')),
                ('temperature', models.SmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(-60), django.core.validators.MaxValueValidator(60)], verbose_name='Температура на складе')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('full_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorehouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pic', models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='Номер картинки')),
                ('img', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('storehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='storage.storehouse', verbose_name='Склад')),
            ],
            options={
                'ordering': ['number_pic'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='номер бокса')),
                ('floor', models.CharField(max_length=3, verbose_name='Этаж')),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='длина')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='ширина')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='высота')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('storehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storage.storehouse', verbose_name='Склад')),
            ],
        ),
    ]
